name: spacex_flutter_app
description: A Flutter app showcasing SpaceX missions, rockets, and launches using GraphQL API.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  nb_utils: ^4.4.8

  # State Management
  provider: ^6.1.2

  # Network & API
  graphql_flutter: ^5.1.2
  dio: ^5.4.3+1

  # Local Storage
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^8.0.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  equatable: ^2.0.7
  mocktail: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/lang/
    - assets/images/
    - assets/icons/
    - assets/animations/
